#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
/usr/bin/chromium --no-first-run --no-sandbox --no-default-browser-check --guest --window-position=0,0 --window-size=1280,720 --temp-profile
